# Generated by Django 5.1 on 2024-08-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shortened_link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pure_link', models.CharField(max_length=300)),
                ('comment', models.CharField(default='No comments stored', max_length=200)),
                ('shortened_link', models.CharField(max_length=30)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('is_valid', models.BooleanField(default=True)),
                ('author', models.CharField(max_length=200)),
            ],
        ),
    ]
