# Generated by Django 5.1 on 2024-08-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortened_link',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
