# Generated by Django 5.1 on 2024-08-31 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_shortened_link_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortened_link',
            name='times_used',
            field=models.IntegerField(default=0),
        ),
    ]
