# Generated by Django 5.1 on 2024-08-31 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_shortened_link_times_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortened_link',
            name='one_time',
            field=models.BooleanField(default=False),
        ),
    ]
