# Generated by Django 5.1 on 2024-08-31 23:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_shortened_link_one_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortened_link',
            name='author',
        ),
        migrations.AddField(
            model_name='shortened_link',
            name='expire_date',
            field=models.DateTimeField(default=datetime.date(2100, 1, 1)),
        ),
    ]
