# Generated by Django 5.1 on 2024-09-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_shortened_link_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortened_link',
            name='expire_date',
            field=models.DateTimeField(null=True),
        ),
    ]
