# Generated by Django 5.1 on 2024-09-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_shortened_link_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortened_link',
            name='comment',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
